### ISSUE TITLE
Release tarballs - wrong folder name

### ISSUE THREAD

**Issue by hannes101** [shimmerproject/elementary-xfce#110]
Hi ochosi,
when downloading the tarball, the folder inside the tarball has the following name "elementary-xfce-elementary-xfce-0.10". I need to adjust that in my spec file in order to remove it. 
I don't know, perhaps it's a github quirk, but I don't think it was there before.
Using wget https://github.com/shimmerproject/elementary-xfce/archive/elementary-xfce-0.10.tar.gz
to download, since using firefox already gives the tarball the double name :-)

Cheers,
Johannes

**Comment by ochosi** [comment]
@hannes101 Indeed, that is weird. I suppose that is because the release has the component name in it, not just the version.

From using git tags, following the "$component-$version" format seems desirable, but indeed, github prepends this by "$projectname", which in most cases will match "$component".

**Comment by ochosi** [comment]
Decided to rename the releases, downloads should look fine again now.

**Comment by davidak** [comment]
>From using git tags, following the "$component-$version" format seems desirable

@ochosi why? i have never seen that
