### ISSUE TITLE
missing icons symlinks

### ISSUE THREAD

**Issue by Mau-G** [shimmerproject/elementary-xfce#132]
While attempting to build the rpm package  for openSUSE, brp-suse (which checks for dangling symlinks as part of qa) complains about the following:

```
[...]
[   17s] calling /usr/lib/rpm/brp-suse.d/brp-25-symlink
[   17s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[   17s]   /usr/share/icons/elementary-xfce/actions/128/media-optical-audio-new.png -> /usr/share/icons/elementary-xfce/devices/128/media-optical-audio.png
[   17s] Add the package providing the target to BuildRequires and Requires
[   17s] calling /usr/lib/rpm/brp-suse.d/brp-25-symlink
[   17s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[   17s]   /usr/share/icons/elementary-xfce/actions/128/media-optical-audio-new.png -> /usr/share/icons/elementary-xfce/devices/128/media-optical-audio.png
[   17s] Add the package providing the target to BuildRequires and Requires
[...]
```
I believe the problem is that it's looking for png files while they are still in svg format. As consequence the build of the package fails.
This is just a fraction of the list of missing links and the full log is in the attachment. 
[log.txt](https://github.com/shimmerproject/elementary-xfce/files/2505171/log.txt)

Here is the link to my  OBS home repo where I'm building the rpm: https://build.opensuse.org/package/show/home:mauriziogalli/elementary-xfce

**Comment by ochosi** [comment]
I'm not a packager, maybe @bluesabre or @jbicha have a clue...

**Comment by maugalli** [comment]
The issue seems to be the svg to png script failing. I managed to make a package anyway by making the spec file installing the directories manually and keeping the icons as svg, rather than making it call the make install method. The package is already on the way to openSUSE distribution.
I could close this issue but I wanted to make you guys aware in case there is a problem with your script that went unnoticed. If you say it's all good then I will close this.

**Comment by ochosi** [comment]
Not sure if Debian uses the make and make install routine at all, that's mostly there for local testing.
