### ISSUE TITLE
edges of xfburn icon not crisp on dark background

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#207]
![preview](https://i.imgur.com/R4r1HuQ.png)

**Comment by philipzae** [comment]
In addition to the crispness of the icon, the barely visible pencil that is symbolizing 'writing' is barely visible and maybe the pencil found in the mousepad icon should be used.

**Comment by Mau-G** [comment]
Not an elementary-xfce icon, but stock xfburn icon. 

Here is a quick one I made:
![image](https://user-images.githubusercontent.com/44322817/79216845-6f832200-7e80-11ea-843f-ff69b37413c9.png)

**Comment by philipzae** [comment]
looks since. anyway to add some lines, like in the xburn icon.
![preview](https://imgur.com/TCELmr0.png)

only noticed with the large version that it pencil and it was a lazer. :D

**Comment by Mau-G** [comment]
I kinda made it as a proof of concept and quickly realised that the pencil would not really be ideal. It looks like a cd labelling icon rather than burning. Laser makes more sense sense but at the moment we’re quite busy with the xfce stock icons so before making new ones here, I would prefer to wait.
