### ISSUE TITLE
Missing Mail Reader icon, wrongly scaled Xfce4-Panel icon

### ISSUE THREAD

**Issue by jesusofsuburbs** [shimmerproject/elementary-xfce#250]
**OS**: Arch Linux
**Xfce Version**: 4.16
**Icon theme version**: master as of 2022-02-20.

I've noticed two not-major-yet-still-bugging things that seem out-of-place:
**1.** The icon for *Mail Reader* in the application menu seems to be that of *hicolor* (i.e. the default as-shipped by Xfce);
**2.** The icon in the "*About xfce4-panel*" dialog seems to be a smaller icon upscaled to fit the proper size, hence making it blurry and pixelated. This doesn't happen with *Adwaita* / *hicolor* icons, nor with a different GTK theme (i.e. it occurs both under *Adwaita* and *Greybird*).

(I was also close to reporting that the xfpm icons weren't properly working under 0.15.2, but then I saw that they were recently properly added / symlinked in master).

These two things would be the finishing touches to what I consider yet one of the best-looking icon themes tailed for Xfce.
Thanks a lot in advance for your time, whether it gets looked at / fixed or not.

**Comment by newhoa** [comment]
Looks like `org.xfce.mailreader` is missing and `org.xfce.panel` is missing at 128px. I'll try to take care of these in a PR soon.

Thanks for reporting!

**Comment by jesusofsuburbs** [comment]
Awesome, thanks again for your efforts!

**Comment by jesusofsuburbs** [comment]
I just found another pair of missing icons: the 'About Xfce' and 'Application Finder'/'Run Program' icons when selected in Application Finder or in the Xfwm4 window switcher are fuzzy as well. They also show up fuzzy under the categories in Application Finder when the item icon size is set to 'Small'.
I think it's the 32x32 symlinks that may be missing, but I'm not fully sure.

Note: this seems to only be the case for elementary-xfce-darker, the other themes show the proper icons.

**Comment by newhoa** [comment]
> I just found another pair of missing icons: the 'About Xfce' and 'Application Finder'/'Run Program' icons when selected in Application Finder or in the Xfwm4 window switcher are fuzzy as well. They also show up fuzzy under the categories in Application Finder when the item icon size is set to 'Small'. ~I think it's the 48x48 symlinks that may be missing, but I'm not fully sure.~
> 
> Note: this seems to only be the case for elementary-xfce-darker, the other themes show the proper icons.
> 
> **EDIT 13-03-2022**: Icons for "Color Profiles", "Log Out", "Removable Drives and Media" seem to be fuzzy in Application Finder when the "Item Icon Size" is set to "Large".
> 
> When set to "Larger", "Appearance", "Default Applications", "Display", "Keyboard", "Notifications", "Panel", "Screensaver", "Window Manager", "Window Manager Tweaks", "Workspaces" also / additionally become blurry.
> 
> When set to "Very Large", "Bulk Rename", "File Manager Settings" also become blurry.
> 
> This 'additional' fuzziness occurs under all variants, btw.
> 
> If you had rather I open a separate issue for these items, do let me know! :)
> 
> Thanks for reading my novel.

@jesusofsuburbs Thanks for taking the time to check all those!

I notice all app icons are blurry on "Small" -- it seems [appfinder uses 36px instead of 32px](https://gitlab.xfce.org/xfce/xfce4-appfinder/-/blob/master/src/appfinder-window.c#L581). So it is scaling down 48px icons. That should probably be reported as an appfinder issue since Xfce generally uses 32px and not 36px and most icon themes don't provide 36px icons.

As for ones you mentioned, I'm not sure the best way to handle those. We could make larger versions of each app icon. But I think it would be best if the app icons were provided by the apps. The new Xfce 4.16 app icons are really nice.

@ochosi should this theme be using the official icons for Xfce apps? It seems that they were [symlinked to other icons here](https://github.com/shimmerproject/elementary-xfce/commit/071c4f7e368da12eaa9f2bf9b941b7d9c5facd41) (mentioned [here](https://github.com/shimmerproject/elementary-xfce/issues/220)) which prevents the official icons from being used (but maybe they were done so to keep the traditional elementary-xfce icons/style).

Removing the symlinks on the org.xfce.* icons would allow the official icons to be used from hicolor.

**Comment by jesusofsuburbs** [comment]
@newhoa While it does seem like an 'issue', I wonder how much sense it would make to file an issue about this in the appfinder repository. If you had a preposition on how to formulate this in a proper way, I'd be very thankful!

I also just came around another 128x128 icon missing: in xfce4-notifyd's about, the icon is also super blurry...
The treasure hunt never ends, haha.

Also, just my 2 cents, even though I don't have much to do with the decision making at all: while the 4.16 icons are nice, they don't really fit the elementary style that well, in my opinion anyway. Though it does seem like a lot less of an inconvenience than having to hunt for and fix every missing symlink out there...
