### ISSUE TITLE
"Save" icon

### ISSUE THREAD

**Issue by mare1203** [shimmerproject/elementary-xfce#341]
In Elementary OS and Libreoffice (with elementary icon theme) icon for save document is with the gray down arrow, not the blue one anymore. Have you thought about adopting this change?
![screenshot_5](https://user-images.githubusercontent.com/109438869/190880182-eac4f63e-c59f-4800-96e0-0efe2531c9cc.png)

**Comment by newhoa** [comment]
Thanks for reporting.

Personally I don't like this icon in either theme, especially with the newer 'partial download' and 'bittorrent' mimetype icons, both of which use a down arrow on a document. Aside from looking like a mimetype, the blue arrow looks too much like the Bittorrent icon, the gray arrow makes it feel inactive or disabled.

I wonder if using a down arrow on an HDD/SDD icon would be better? Or some other sort of symbol or emblem. Any thoughts or idea would be appreciated.

This might be worth opening an issue for upstream and something we could work on in elementary icons first.

**Comment by ochosi** [comment]
The style for this icon changed a few times upstream and I can't recall which one was there before, but when I started the LibreOffice elementary icon theme they were in sync.

Using HDDs or SDDs for the 'save' metaphor feels quite oldschool (think: floppy) and these metaphors are not only lost on less-technical users (who might not know what a HDD looks like) but are also prone to getting out of date.

In general I would say that If you're truly unhappy with the style of an icon or the metaphor report it upstream. After all, this theme is mostly a shim with some extras.

**Comment by marko1231991** [comment]
> Aside from looking like a mimetype, the blue arrow looks too much like the Bittorrent icon

Until a few years ago, the save icons in Elementary OS/Xubuntu operating systems, Libreoffice and the torrent icon were identical, with a blue downward arrow. My assumption was that therefore in Elementary OS and Libreoffice after that they changed the icon to a new one with a gray arrow, to avoid the sameness with the torrent icon.

**Comment by mare1203** [comment]
> ...the gray arrow makes it feel inactive or disabled. If changing the arrow color, I think orange or red would be better as writing/saving can be a destructive action.

under the impression of what you wrote, now I'm really starting to see save icon in LibreOffice as disabled or inactive...
maybe this one with the red arrow makes more sense...

**Comment by newhoa** [comment]
How about using the "Download" folder icon?

![document-save-prop](https://user-images.githubusercontent.com/1984060/209433307-10147ee2-cfb4-41a4-9c3f-66135170634d.png)

**Comment by rizmut** [comment]
Hi LibreOffice icons maintainer here.

Personally I prefer disket for save icon as it widely accepted though is not technically ideal. For elementary, I always try to keep sync up with upstream. The save icons in LibreOffice has different state. Previously, blue arrow indicates saved or unchanged document and red allow indicates unsaved one. Now they are the same grey down arrows with additional red circle below for unsaved state.

**Comment by newhoa** [comment]
@rizmut Sorry for the late response! I really enjoy and appreciate the work you've done on LibreOffice. You've done a really great job keeping LibreOffice looking nicer all the time (and I've read and enjoyed some of your UI blogs before)! So thank you!

I like the diskette as well, but that idea has been shot down by all maintainers and some users, so it's not very popular I guess haha. I do like the idea of different icons for the different save states like LibreOffice uses. I wish FreeDesktop would add that to the spec and/or more editors would use it.

We did talk a little more about the save icon upstream [here](https://github.com/elementary/icons/issues/1168) and decided (I think) at least on a new Save Document icon; one that matches more the newer upstream document action style, like Document Import/Export.

The upstream PR for that is [here](https://github.com/elementary/icons/pull/1230) if you'd like to take a look and/or comment.

Danielle Fore suggested the same down arrow with a folder for "Save As" since it brings up the folder chooser, which makes sense. But I tried a few versions of that and it didn't look great to me. So any other ideas for that from anyone would be appreciated. I'll try again with the folder thing eventually, maybe it'll turn out better next time I try.

**Comment by newhoa** [comment]
The changes for this were finalized upstream, made PR  #437 for it to pull from upstream if anyone would like to check it out.

Example from upstream:

![save-icons](https://private-user-images.githubusercontent.com/7277719/327218280-ad696d9f-65db-4536-be81-9eb8d7cb5a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTk1MjIsIm5iZiI6MTcyMjE1OTIyMiwicGF0aCI6Ii83Mjc3NzE5LzMyNzIxODI4MC1hZDY5NmQ5Zi02NWRiLTQ1MzYtYmU4MS05ZWI4ZDdjYjVhNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMDkzMzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg1NWZkYjYzZmY3ZGJhN2NhNzRkMWRiMGQ4OTk2ODFkNTYzMmQ2MDBjZTEyYTMxMjdkMTY2NTNjZTBjOTkyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uROk52AGhH5LqIP6ILlDcztrpJ5x9VGexN1RQ93j75A)
