### ISSUE TITLE
Mousepad missing close icons on tabs

### ISSUE THREAD

**Issue by duck7000** [shimmerproject/elementary-xfce#363]
With elementary xfce dark those icons are missing, so it is difficult to close a tab. if you hover mouse you can see a little gray cross
Could you add those icons? The standard version has those icons but the dark variant apparently not.

![Screenshot_2023-01-06_21-38-50](https://user-images.githubusercontent.com/15360048/211096676-1982e18a-81c8-4790-9d9e-663fa584e30a.png)

**Comment by newhoa** [comment]
Thanks for reporting!

This is already fixed in the current git.

If you don't want do download/build from git you can copy the `elementary-xfce/actions/16/window-close.png` icon to `elementary-xfce-dark/actions/16/` and next time you log back in it should use the new icon. Or if you prefer the style of `actions/symbolic/window-close-symbolic.png` you can copy that to darker's actions/16 folder and rename it to `window-close.png`.

Hope this helps!

**Comment by duck7000** [comment]
Thanks a lot for fixing, i installed git version and it works fine now!

**Comment by bluesabre** [comment]
Thanks for the follow-up! Closing this one out.
