### ISSUE TITLE
djvu and pdf files got the very same icons in file manager

### ISSUE THREAD

**Issue by splate07** [shimmerproject/elementary-xfce#392]
steps to reproduce:
download latest release, open terminal and execute the following
tar -v -t -f elementary-xfce-0.17.tar.gz --wildcards '*djvu*'
you would see that image-vnd.djvu*.svg is just a symbolic link to application-pdf.svg. 

So, if one is about to install djview4 for viewing *djvu files, one would be confused because djvu files have the same icons as pdf files in file manager.

BTW, this bug was introduced a couple of releases earlier, 
version 0.15.x is ok and has got no such symlinks for djvu icons

**Comment by newhoa** [comment]
Thanks for the report.

djvu was made a symlink to pdf (like postscript) because they all open with the document viewer. Previously djvu files would default to either an image or libreoffice/word document icon, which were both wrong, so the document viewer icon (which pdf uses) seemed to make the most sense.

But yeah, it seems to block the mime icon installed by djview4. Although that icon doesn't go with the theme (and not having an icon for it so the djview4 icon could be used would cause the issue above where people without that app would have the wrong icon).

Would making the document icon purple for djvu files be enough to identify them? That way it would still have the same style as the document icon, but use the djvu colors and be easy to differentiate.

![image-vnd djvu](https://github.com/shimmerproject/elementary-xfce/assets/1984060/ad2fb015-49b2-4916-bb36-fcf8b63d12f3)

That's what I'd most lean toward I think. Any thoughts on that or suggestions?
