### ISSUE TITLE
NetworkManager while connected to a VPN icon looks weird in XFCE Panel

### ISSUE THREAD

**Issue by sudcapitano** [shimmerproject/elementary-xfce#433]
Same as the title. See the screenshot below. I remember on Xubuntu it shows a big lock icon instead. Not sure why it shows this on Arch. 

![immagine](https://github.com/shimmerproject/elementary-xfce/assets/155137455/d90299c3-1507-4476-9511-2b79f7120cf3)

You can see it doesn't look right. The small lock icon is not above the Ethernet icon it looks like it is attached and it is not outlined either. It is overlapping, maybe change it to the same one that Xubuntu uses?

**Comment by newhoa** [comment]
Thanks for reporting!

Ok, this took me a while to figure out since Arch, Xubuntu (and Fedora) all use this same theme. So it's some kind of app or config difference with either the distro or nm-applet.

It looks like Xubuntu/Ubuntu uses a different configuration or installation method of nm-applet? When I check the Xfce panel Status Tray plugin, Network Manager Applet shows as:

- Xubuntu: Status Notifier
- Fedora: Systray (this is showing the same problem as Arch)

When nm-applet shows as a Status Notifier the icon is replaced in every state change (so the "Connecting" animation replaces the Ethernet/Wifi icon, and the full VPN lock icon replaces the Ethernet/Wifi icon).

When nm-applet shows as Systray the Ethernet/Wifi icon always remains and the animations and VPN icons act as emblems and overlap the existing icon.

I'm not sure exactly how to completely fix this on both sides from an icon theme perspective. At the very least the lock emblem could be changed from white to the yellow/orange (it's only white in the "dark" variant). This still doesn't look good when the icon is set to anything less than 24px though since the lock sits on top of the bottom right square.

We have been colorizing non-symbolic icons recently, and since Systray icons are always non-symbolic that might help a little more.

**Comment by newhoa** [comment]
@sudcapitano See if you can start nm-applet as an indicator. The indicator flag (at launch or build, I'm not sure) seems to be what makes it show as a StatusNotifier in the Xfce Status Tray.

```bash
killall nm-applet
```

```bash
nm-applet --indicator
```
This works on Fedora, so hopefully it will work on Arch. It may require `libappindicator-gtk3` for this to work. It's also possible `libappindicator-gtk3` might be required to be installed before building/installing `network-manager-applet` if it looks for that as an optional build flag.

**Comment by sudcapitano** [comment]
Thanks so much, I just tested it and that seems to fix it. I really appreciate your work by the way. Every time I install XFCE I instantly get this icon pack.
