### ISSUE TITLE
16x16 file manager icon now has the "home" emblem, is this intentional?

### ISSUE THREAD

**Issue by HolyBlackCat** [shimmerproject/elementary-xfce#494]
Apparently [this change](https://github.com/shimmerproject/elementary-xfce/commit/342e469676e3a6aeb1b922035e4c338cdea01048#diff-72ab56802f79a8a43ea0ed29a852675ef27da7a731b751e1c4cfab1721ddbb6b) finally landed in the AUR.

Now the tiniest file manager icon `elementary-xfce/apps/16/system-file-manager.svg`, has the "home" emblem on it, but it used not to.

Just wanted to ask if this change is intentional or not.

**Comment by newhoa** [comment]
It is intentional. We try to keep icons as consistent as possible across all sizes. It also mirrors the way upstream does it as they include the emblem on the 16px version (although they are using the magnifying glass instead of the home symbol). If it's causing some sort of issue let me know though. Thanks!

**Comment by HolyBlackCat** [comment]
No issue, I'm just not used to the new look. :slightly_smiling_face: 

I guess I'll close this.
