### ISSUE TITLE
Steam icon

### ISSUE THREAD

**Issue by Yanpas** [shimmerproject/elementary-xfce#76]
I was chatting with ochosi in freenode. I don't know how to commit file, so I have create and issue. Attaching archive with 4 icons for steam app
https://www.dropbox.com/s/8yxspi9vow2gcn3/elementary-xfce.zip?dl=0

**Comment by ochosi** [comment]
Sorry, but all icons added to this icon theme have to be in svg format.

**Comment by Yanpas** [comment]
Converted them to svg, placed to system folder, steam doesn't read them. Even if the picture is jpg. So how should the patch look? Should I place svg and you will add code lines to convert them to png or should I convert them to png and place svgs in the same directory?

**Comment by ochosi** [comment]
Sorry, I can't really help you with that as I'm not using Steam and also not planning to.
Generally speaking the svg icons in the theme are converted to png (at least for Xubuntu) because png loads faster. However, the source icons in the theme have to be svg for easier maintenance.

Another note: please submit the icons in the correct folder/context that they're going to be used for. (If it's a panel-icon then put it in the panel folder etc.)

**Comment by Yanpas** [comment]
Created pull request https://github.com/shimmerproject/elementary-xfce/pull/77

**Comment by Yanpas** [comment]
Guess the patch will be applied when one of developers who use steam will test it?

**Comment by ochosi** [comment]
Yes, I'd say so.
