### ISSUE TITLE
Audio icons size 24 are dark

### ISSUE THREAD

**Issue by Yanpas** [shimmerproject/elementary-xfce#80]
elementary-xfce-dark/panel/24/audio-volume*.svg - 4 icons are dark, but must be light

**Comment by Yanpas** [comment]
16 size icons, which are symbolic links, are dark too

**Comment by ochosi** [comment]
Where exactly is that a problem?

**Comment by Yanpas** [comment]
Hope these screenshots will clarify the issue. I'm using elementary-darker icons.
![_2015-04-04_14-46-42](https://cloud.githubusercontent.com/assets/7345761/6992479/ba242868-dad9-11e4-8851-26dbd23a5c40.png)
![_2015-04-04_14-47-20](https://cloud.githubusercontent.com/assets/7345761/6992478/ba231e28-dad9-11e4-8681-03333c45eba6.png)
![_2015-04-04_14-47-38](https://cloud.githubusercontent.com/assets/7345761/6992480/ba28df98-dad9-11e4-84de-f4b333c0c72c.png)

**Comment by Yanpas** [comment]
Guess I should open an issue for network icon too

**Comment by ochosi** [comment]
Not sure what plugin you're using but this problem is unavoidable. There's simply no way to generally fix this, because the 24px icon is used in many other contexts (e.g. the mixer's settings dialog). Same thing is true for the 16px icons (e.g. all menu-items).

The only real solution here is for plugins to use symbolic icons, which will be automatically recolored. (E.g. xfce4-pulseaudio-plugin)
